### ISSUE TITLE
The action threatens maintainer response on prs with a net positive increase in gbp.

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/gbp-action#22]
On one hand I get the constant reminder aspect, but this just seems wrong somehow.
Example: https://github.com/tgstation/tgstation/pull/57273

**Comment by Mothblocks** [comment]
So, the gbp-action end of this is fixed. It's not working on tgstation because there's a separate problem--there's a race condition.

The webhook and action fire off at the same time, and so gbp-action has to be slower than the webhook in order to see the new labels. If the auto labeler was a GitHub action, this bug wouldn't be happening. In the meantime, I think the best solution is just applying an artificial delay in the workflow file itself. However, that'll accentuate #24 until it's fixed, since that too is a race condition!
