### ISSUE TITLE
Use empty branch for storing the data.

### ISSUE THREAD

**Issue by AnturK** [tgstation/gbp-action#23]
Instead of using master/workflow branch to store it create empty gbp_store/configurable empty branch with only the tally file.
Would keep the update commits out of main history.

**Comment by LemonInTheDark** [comment]
Seconded

**Comment by Mothblocks** [comment]
@affectedarc07 expressed a separate need solved by this--they have branch protection on master, and so GitHub Actions cannot push there.

This is definitely a must, I'll get to it when I can.

**Comment by Mothblocks** [comment]
Okay, after the race condition of #24, the path I want to go down is an empty branch where every contributor is their own file which contains their amount of points.

Since they'll be on their own branch, it won't clog up the directory, and it'll stop the race condition of the file being updated in two places at once (unless you merge a PR from the same guy very fast).

**Comment by AffectedArc07** [comment]
So long as it's still a directory inside the empty branch, otherwise people will tab into the branch and have their PCs feeeze as 3 billion files in the initial dir load in

**Comment by Mothblocks** [comment]
I was thinking the branch wouldn't be based on master at all, just like gh-pages.

**Comment by Mothblocks** [comment]
Oh, I see what you mean. Yeah, sure, might as well throw a README in there anyway.
