### ISSUE TITLE
GBP theft on your repo!? It's more likely than you think.

### ISSUE THREAD

**Issue by spessbro** [tgstation/gbp-action#24]
Apparently when merging prs quickly github-action will not let the last action finish before starting the next one causing it to overwrite the last gbp change.

https://github.com/tgstation/tgstation/commit/bd40607e8978af71cc180857fcbff693485f035d
https://github.com/tgstation/tgstation/commit/bd40607e8978af71cc180857fcbff693485f035d

these are the two instances of this happening i could find.

**Comment by optimumtact** [comment]
this is so sad

**Comment by optimumtact** [comment]
@Mothblocks

**Comment by Mothblocks** [comment]
It's because `createOrUpdateFileContents` replaces the entire data, instead of diffs. It's a race condition against itself.

GitHub's API doesn't have a good solution for this, so we'll have to make the action use git directly.

**Comment by Mothblocks** [comment]
What could also be done is instead of just one big gbp-balances.toml (since with diffs, it's possible to conflict), we take #23 and create a file for every contributor, with the contents being their points. I don't know if that's more or less stupid honestly, they wouldn't take up much space at all.
